# Generated by Django 5.1.5 on 2025-02-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0002_gadget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='latest_images/')),
                ('category', models.CharField(choices=[('france', 'France'), ('memes', 'Memes'), ('tech', 'Technology'), ('politics', 'Politics')], max_length=50)),
                ('author', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
