# Generated by Django 5.1.5 on 2025-02-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
